---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: README.md
  label: Welcome
- type: heading
  label: Content
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: hugo serve --renderToDisk
  output_directory: public
version: 0.38.1
